### PR TITLE
Fix - overview heading animates in too late

### LINKED ISSUE #4: On mobile, the overview heading animates in too late
https://github.com/willywill/site/blob/dadfc32376a052dde456d00d07f94e63e798a558/components/composite/Overview/index.js#L13

`data-aos-offset` should be updated to a number that works well on desktop and mobile

### PR DESCRIPTION
**Pull request by willywill**
Fixes #4

### CODE REVIEW

File: components/composite/SectionHeading.js [hunk 1]
```diff
@@ -56,7 +55,6 @@ const SectionHeading = ({
       <Flex column>
         <Heading
           data-aos="fly-in"
-          {...animationProps}
```
Comment (willywill) [inline components/composite/SectionHeading.js:59]: Getting rid of more bad practices. A win-win 😃
